import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@repo/ui/components/ui/toaster";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Icons } from "@repo/ui/components/icons";
import { TooltipProvider } from "@repo/ui/components/ui/tooltip";
import { SocketProvider } from "@/contexts/socket-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <SocketProvider>
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <TooltipProvider delayDuration={0}>
              <body className={inter.className}>
                <ClerkLoading>
                  <div className="flex items-center justify-center h-screen">
                    <Icons.logoLoading className="size-18 fill-foreground" />
                  </div>
                </ClerkLoading>
                <ClerkLoaded>{children}</ClerkLoaded>
              </body>
              <Toaster />
            </TooltipProvider>
          </ThemeProvider>
        </ClerkProvider>
      </SocketProvider>
    </html>
  );
}
